version: '3.8'

services:
  app1:
    container_name: app1
    build:
      context: .
      dockerfile: Dockerfile
    command: nx serve app1 --port=3001
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network


  app2:
    container_name: app2
    build:
      context: .
      dockerfile: Dockerfile
    command: nx serve app2 --port=3002
    ports:
      - '3002:3002'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network


  app3:
    container_name: app3
    build:
      context: .
      dockerfile: Dockerfile
    command: nx serve app3 --port=3003
    ports:
      - '3003:3003'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
